### ISSUE TITLE
Codestyle : Standard

### ISSUE THREAD

**Issue by Xstoudi** [ES-Community/es_bot#1]
Plop !

Que diriez-vous d'utiliser le codestyle [StandardJS](https://standardjs.com/rules.html) ?

Histoire de mettre à place le style de code à adopter.

**Comment by fraxken** [comment]
Oui cela serait une bonne idée. Néanmoins je suis pas super fan du Tab 2 (surtout avec async/await).

**Comment by Vahelnir** [comment]
Je trouve que c'est une très bonne idée et tab 2 ftw

**Comment by Xstoudi** [comment]
Pourquoi @fraxken est-ce particulièrement un problème avec async/await ?

**Comment by RomainLanz** [comment]
Hello 👋 

StandardJS est un standard simple et assez flexible, j'approuve donc ce choix.

D'ailleurs, indenter son code avec 2 espaces et un standard utilisé par énormément de "CodingStyle" (par exemple le plus connus, [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript#whitespace)) ou de "Beautifier" par défaut.

**Comment by DeltaEvo** [comment]
Licorne 🦄 

Je vien annoncer que je n'approuve pas l'utilisation des espaces pour l'indentation comme ça personne rale pour le nombre de place que ça prend @fraxken pourra mettre ces tabs à 4 espaces et @RomainLanz à 2, donc faites pas chier :kappa:

Voila c'etait l'avis inutile d'un Delta Sauvage

**Comment by fraxken** [comment]
Le linter est configuré sur le style standard !
