### ISSUE TITLE
💡 (idée) Système de votation

### ISSUE THREAD

**Issue by Westixy** [ES-Community/es_bot#15]
Etant donné le nombre de membre grandissant et du nombres d'éléments a voter dans la communauté, je penses qu'un moyen de voter de manière anonymisée et unique sur des points précis devient intéressant. Actuellement c'est un peu au feeling ("dans les grandes lignes c'est plutôt accepté/refusé") et personnellement ça me dérange.

Donc voici comment je vois la chose : 
- une issue/PR est ouverte sur github
- après plusieurs jours que tout le monde ait pu donner son avis, un mentor clos l'issue
- un mentor lance une votation (si validée) à l'aide du bot en référant l'issue, ceci a pour effet de mettre un message dans annonce ou par mp a chaque membre.
- Chaque membre peut voter 1 fois durant les 7 prochains jours `+` oui ; `-` non ; `0` blanc (de manière anonyme via mp au bot)
- Après le delai, le bot donne le résultat dans le chan annonce ou un nouveau nommé votations (why not) avec  le nombre de votant  et le pourcentage de chaque réponses.

pour moi il faut que l'on améliore la façon de prendre des décisions, ceci n'est qu'un ébauche d'une possibilité de faire avec le bot si vous voyez une façon de faire différente ou plus intéressante je suis preneur.

**Comment by Xstoudi** [comment]
C'est ce qu'on fait en pratique en fait, sans bot.

**Comment by fraxken** [comment]
Je suis d'accord avec Xavier (c'est déjà ce que nous faisons avec les Emojis etc). Bref je suis contre cette commande qui finalement nous compliquera sûrement la tâche plus qu'autres choses !

**Comment by Purexo** [comment]
Yep, je rejoins @Xstoudi et @fraxken , un bon vieux message avec des émoji réactions est suffisant.

**Comment by Westixy** [comment]
Ok alors je peux clore l issue :)
