### ISSUE TITLE
L'évenement 'ready' se fait appeler plusieurs fois 

### ISSUE THREAD

**Issue by Xstoudi** [ES-Community/es_bot#3]
Comme le montre cet extrait de log :
```
5/20/2018 4:25:40 PM> escommunity_bot@1.2.0 start /es-bot
5/20/2018 4:25:40 PM> node index.js
5/20/2018 4:25:42 PM ES Bot up and ready
5/25/2018 12:42:31 AM ES Bot up and ready
```
il semblerait que la partie 'ready' de Discord.js se trigger plusieurs fois ce qui a pour effet de dédoubler le feed Twitter ou le feed des membres entrants/sortants.

**Comment by fraxken** [comment]
La pull-request #4 devrait corriger le problème en empêchant une double initialisation. Il doit y avoir un problème de fond plus important à corriger mais cela empêchera déjà les problèmes rencontré actuellement.

**Comment by Xstoudi** [comment]
Le système de boolean doit se situer au niveau global de l'event 'ready', pas uniquement dans l'event de Twitter.
