### ISSUE TITLE
[FEATURE] Mention user when weektalk is about to begin

### ISSUE THREAD

**Issue by HZooly** [ES-Community/es_bot#6]
Maybe we could add feature to the ES Bot that allows users to:
- Subscribe to weektalk: `.weektalk sub/unsub`

If user is subscribed, _weektalker_ fires an event, and ES Bot DM all of subscribers that a talk is about to begin.

**Comment by Westixy** [comment]
Je suis pour mais tant qu'à ajouter un système pour alerter que certaine personne pourquoi pas ajouter une commande permettant de le faire pour différents thèmes. 
ex: `!sub weektalk` `!sub whatever` et un `!alert whatever`

**Comment by Xstoudi** [comment]
Dans les faits c'est pas une mauvaise idée, et je préfère effectivement la version de @Westixy. Je reste cependant sceptique sur un point : qu'est-ce/qui est-ce qui trigger les alertes ?

**Comment by HZooly** [comment]
J'imagine quelque chose du genre : quelqu'un qui possède les droits (Mentor ou Talker par exemple) peut DM le bot, avec un `!weektalk starting` ou `!whatever starting`

**Comment by Westixy** [comment]
Un call sur chaque Nick de chaque personne style 
```
!alert some
-> @Westixy @Zooly ...
```
ou un message privé mais je préfère la première version

**Comment by Purexo** [comment]
Étant donné que nous somme une communauté francophone, je vais répondre en Français.

@Westixy m'a un peu devancé mais je vais aller plus loins dans les détails technique.

```
// les commandes prenne comme context le chan dans lequel ce trouve la personne effectuant la commande
// commandes publiques
!subscribe
!unsubscribe
// commandes admins (avoir le role de Mentor ?)
!alert message
```

Quand une alerte est lancé, toutes les personnes ayant souscrit au chan sont mentionné dans le #chan concerné.

Example - @Westixy et @Purexo ont subscribe à #weektalk, @fraxken annonce le début du weektalk :

Fraxken : `!alert Le weektalk commence, vous pouvez nous rejoindre sur https://framatalk.org/weektalk-3 pour participer comme invité ou sur [insérer adresse de live twitch ou youtube] comme spectateur`
ES Community BOT : @Purexo @Westixy

**Comment by Purexo** [comment]
Si aucun message n'est fournis avec `!alert` le bot répond :  
Pour éviter le spam (volontaire ou non) merci de fournir un message pour cette alerte.

**Comment by Westixy** [comment]
Du coup l alert serait directement liée au channel

**Comment by Purexo** [comment]
C'est l'idée oui.

Ça permet d'avoir une interface générique pour ne pas lier une commande à un truc précis. (et c'est d'autant plus simple à utiliser)

**Comment by Purexo** [comment]
Après on peux toujours discuter de la terminologie des commandes, de leurs alias, de possible alias, d'arguments optionnels, etc... Mais c'est presque secondaire.

```
!subscribe // souscrit au chan courant
!subscribe #chan // souscrit à chan
!subscribe @Purexo // doit être admin, souscrit Purexo au chan courant
!subscribe #chan @Purexo // doit âtre admin, souscrit Purexo à chan
// + equivalent pour unsubscribe

!alert message // alerte les personne ayant souscrit au chan courant
!alert #chan message // alerte les personnes ayant souscrit à #chan (et le bot répond dans #chan en répétant le message du coup)
```

pour les alias :
```
!sub // alias de !subscribe
!unsub // alias de !unsubscribe
```

**Comment by Westixy** [comment]
Possible implémentation : https://github.com/Westixy-FORK/es_bot/tree/feature_channel-subscribe

**Comment by Westixy** [comment]
Peut-on clore l'issue ou on la garde pour discutier de l'implémentation ?

**Comment by Xstoudi** [comment]
Si vous voulez discuter de l'implémentation réouvrez en une.
