### ISSUE TITLE
Fonctionnalité + Nouveau Salon pour s'ajouter une rôle.

### ISSUE THREAD

**Issue by MobElian** [ES-Community/es_bot#8]
L'idée serait de développer une nouvelle commande permettant de s'ajouter un rôle automatiquement et aussi de s'en enlever un. Et bien sûr, ceci dans une salon dédié.

**Comment by Purexo** [comment]
pas besoin que ce sois dans un salon dédié je pense.

Mais oui, il est déjà prévu d'ajouter cette fonctionnalité au bot.
